596 add initial container and ops implementations for parallel dense backend
Algebraic-Programming/ALP pull request #129
Opened 2022-11-18 13:50 UTC by vdimiczrc

2022-11-21 08:49 UTC, hidanielesgit commented on CMakeLists.txt
> +option( WITH_ALP_OMP_BACKEND "With OMP Dense backend" ON )
Perhaps one question related to the build & test changes would be, are these changes in line with current [docs](https://github.com/Algebraic-Programming/ALP/blob/master/docs/Build_and_test_infra.md ) or did you have to diverge in any ways? If so we should at least keep track of this for integrating into the official documentation at some point.

2022-11-21 10:52 UTC, hidanielesgit requested changes

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/matrix.hpp
> +				typename SourceMatrix::template view_type< view::cross_backend >::type
`cross_backend` might not be needed (see type_traits comments)?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storage.hpp
> +	class Distribution {
Should this be `BlockCyclicDistribution` ? `Distribution` might become parent if needed. Should define it within a namespace (eg, `distributions`)?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storagebasedmatrix.hpp
> +					Vector< T, omp >,
maybe prepend witrh `internal::` to make clear the nature of the container?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storagebasedmatrix.hpp
> +					return amf.getStorageIndex( i, j, s, P );
what are `s` and `P` here? I recall we where leaving them as placeholder for parallel concepts but now that we are implementing them I wonder if these became redundant.

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storage.hpp
> +					size_t block_width = 0;
Is this temporary?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storage.hpp
> +					return 1;
Is this temporary?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/storage.hpp
> +					return 0;
Is this temporary?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/vector.hpp
> +						#pragma omp critical
Should this region be enabled only in DEBUG mode?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/vector.hpp
> +					std::cout << "Entered OMP internal::Vector constructor\n";
Debug print out?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/vector.hpp
> +						delete [] buffers;
I think each buffer entry be deallocated (ie, need to  `delete[] buffers[ thread ]` ) before delete[]-ing buffers?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/reference/vector.hpp
> +					n( length ), cap( std::max( length, cap ) ), initialized( false ), should_free_data( true ) {
With `should_free_data`, are we creating a shared_ptr-like logic here? Perhaps we should just switch to smart pointers?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/views.hpp
> +			cross_backend,
See comment about `cross_backend` in `type_traits.hpp`.

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/views.hpp
> +		struct CrossBackend {
Same here.

2022-11-21 10:52 UTC, hidanielesgit commented on src/alp/omp/init.cpp
> +alp::RC alp::init< alp::omp >( const size_t s, const size_t P, void * const data ) {
(Similarly to other comments elsewere) What are `s` and `P`?

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/io.hpp
> +					Scalar< InputType, InputStructure, reference > ref_val( *val );
See previous comment about parametrizing the local backend choice.

2022-11-21 10:52 UTC, hidanielesgit commented on include/alp/omp/io.hpp
> +					Scalar< InputType, InputStructure, reference > ref_val( *val );
Perhaps we should have have a way to construct from alp::Scalar with different backend to avoid going through access operator?

2022-11-24 12:40 UTC, hidanielesgit approved these changes

2022-11-24 12:40 UTC, hidanielesgit commented on include/alp/omp/matrix.hpp
> +			using original_amf_factory = alp::storage::AMFFactory< config::default_sequential_backend >::FromPolynomial<
Do we need the factory or could we get the amf_type directly from the source type rather than recreating it?

2022-11-24 12:40 UTC, hidanielesgit commented on include/alp/omp/matrix.hpp
>  			const auto &distribution = getAmf( source ).getDistribution();
How do we make sure that the amf is distributed? Perhaps we should statically check based say on its backend?

2022-11-24 13:05 UTC, djelovina commented on include/alp/omp/exec.hpp
> +			Launcher( const size_t process_id = 0,
newline  after `(`

2022-11-24 13:08 UTC, djelovina commented on include/alp/omp/scalar.hpp
> +				// }
why is this commented?

2022-11-24 13:15 UTC, djelovina commented on tests/unit/dense_omp_matrix.cpp
> +int main( int argc, char ** argv ) {
remove space after `**`

2022-11-24 17:05 UTC, merged