664 missing assertions for threaded execution
Algebraic-Programming/ALP pull request #284
Opened 2024-01-29 15:48 UTC by byjtew

Closes #278

2024-01-29 15:59 UTC, anyzelman requested changes

2024-01-29 15:59 UTC, anyzelman commented on include/graphblas/reference/vector.hpp
> +#endif
Put all of this in a `#ifndef NDEBUG`

2024-02-29 13:27 UTC, anyzelman commented
Ready to merge

2025-10-22 07:44 UTC, GiovaGa commented
@anyzelman this seems solved, I don't know if we want a clearer error message to be outputted instead of a possibly cryptic assertion error.
I will run unit tests on the internal CI just to be sure, but should be good to go

2026-01-13 16:41 UTC, anyzelman commented
I rebased again, reviewed it, and running smoke + unit tests with LPF now (in addition to CI).

Changes during review: I made the check a function of the Coordinates class, as otherwise it is not easy to call for a check without a lot of code repetition. I also modified the internal::getCoordinates for const-coordinates to perform the check. I did not think the modification to config::OMP was needed and reverted that, instead relying on its already-established threads function call.

There is one annoyance that in the use of the coordinates class, a callee tends to call a third class for creating the buffer, and then passes that into Coordinates. This means that the number of threads is actually controlled by this third class. The current design in this MR is hence not totally robust if somehow the number of threads spawned during a parallel section changes between the time the third party class code executes and allocates the buffer for some T1 #threads , and the time the #threads is actually recorded when the coordinates instance is set while some other T2 #threads is active.

2026-01-14 11:23 UTC, anyzelman submitted a review, later dismissed

2026-01-14 11:39 UTC, anyzelman commented
Concept release notes (all unit tests with LPF still running on the latest commit):

Benjamin (@byjtew) noticed, once upon a time, that should users manually modify the number of threads available to OpenMP _while_ the application is running, the application could crash without a clear error message. This issue recently resurfaced and this MR fixes at least some instances of this by implicitly checking if thread-counts remain the same whenever the sparse accumulator (SPA) of vectors or sparse matrices is retrieved. This check, however, has non-trivial overhead and is only active in debug mode. The end-user advice hence, as always, is to enable debug mode should their application crash for unclear reasons.

The implementation of the check is constrained in that it assumes thread counts will not change between allocating SPA buffer data and assigning that buffer to a SPA. While the ALP internals guarantee that no such change occurs from within ALP, it is conceivable that such a run-time thread-count change could be concurrently initiated by a user thread, which in turn could be timed unfortunately so that this assumption is indeed violated. We consider this a rather adversarial case that would not be worth the implementation effort to guard against, but do note this caveat here in the commit notes.

Thanks also to @GiovaGa for recently revisiting this MR and again to Benjamin for flagging the issue and providing the initial fix, now finally merged.

2026-01-14 12:25 UTC, anyzelman approved these changes

2026-01-15 07:59 UTC, anyzelman commented
All tests OK, merging

2026-01-15 08:00 UTC, merged