Issue #261: adding missing dense descriptor and delete unnecessary se…
Algebraic-Programming/ALP pull request #288
Opened 2024-01-31 15:54 UTC by aristeidis-mastoras

adding dense descriptor

2024-02-15 11:34 UTC, anyzelman requested changes
Please see the review comments -- also one question: should allowing a dense descriptor to eWiseLambda not also lead to a change in a cpp file src/nonblocking/ somewhere?

2024-02-15 11:34 UTC, anyzelman commented on include/graphblas/base/blas1.hpp
> -		const Vector< DataType, backend, Coords > & x, Args...
Why are the varargs removed here?

2024-02-15 11:34 UTC, anyzelman commented on include/graphblas/hyperdags/blas2.hpp
> +			internal::getVector(mask),
I think it's clearer if these two are grouped (and similar further down for u and v_mask--- I agree the matrix could/should go on its own row)

2024-02-15 11:34 UTC, anyzelman commented on include/graphblas/nonblocking/blas2.hpp
> +		Descriptor descr = descriptors::no_operation,
This descriptor is not passed to the subsequent call to eWuseLambda (line 1551 below)

2024-02-15 11:34 UTC, anyzelman commented on include/graphblas/reference/blas1.hpp
> +		Descriptor descr = descriptors::no_operation,
The function should return illegal if x was not dense but the dense descriptor was passed (maybe this check is also missing with the other backends)

2024-02-15 11:34 UTC, anyzelman commented on include/graphblas/reference/blas2.hpp
> +		Descriptor descr = descriptors::no_operation,
(it seems forgotten here as well -- note that the dense descriptor is only defined to apply for vectors (x), and not for A)

2024-02-15 11:36 UTC, anyzelman commented
Note: I also added the todo of removing the invert_mask in the PR algorithm. If no objection I could do that quickly around now?

2024-02-15 12:46 UTC, anyzelman commented
> Note: I also added the todo of removing the invert_mask in the PR algorithm. If no objection I could do that quickly around now?

This is done. I did run into a new bug in nonblocking, I opened issue #305 for it.

2024-02-20 09:47 UTC, byjtew commented on include/graphblas/base/blas1.hpp
> -		const Vector< DataType, backend, Coords > & x, Args...
Because they are never implemented

2024-02-26 15:50 UTC, anyzelman commented
@aristeidis-mastoras @byjtew -- this one is now conflicted but was the next on my list. I'll try resolve the conflicts now

2024-02-26 18:23 UTC, anyzelman commented
Rebase complete, smoke tests with LPF OK. Unit tests with LPF and GitHub CI running overnight

2024-02-26 18:23 UTC, anyzelman commented
(If anyone of @aristeidis-mastoras @byjtew wants to review how I handled the conflicts lemme know before tomorrow -- if no message by e.g. noon, I'll proceed with review/merge:)

2024-02-26 18:25 UTC, anyzelman commented
Crossref #305 which this MR should also fix (TBC)

2024-02-27 11:18 UTC, anyzelman submitted a review, later dismissed

2024-02-27 11:18 UTC, anyzelman commented
Review OK but found one issue in the bsp1d backend. Re-running smoke & unit tests with LPF.

2024-02-27 12:53 UTC, anyzelman commented
All tests OK, will merge

2024-02-27 12:59 UTC, anyzelman commented
Concept release notes:

Prior to this MR, the PageRank implementation does not pass the dense descriptor when it could, while it includes the use of the expensive `invert_mask` in its performance-critical loop. Mask inversion is expensive since it requires iterating over the full vector range, while, in this case, the inverted mask is constant. Hence, this MR introduces the following changes:
- the inverted mask is precomputed once, while in the performance-critical loop the precomputed inversion is reused as a structural mask; and
- the PR algorithm is reviewed to pass the dense descriptor whenever possible.

In implementing these fixes, the following feature has been added:
- the `grb::eWiseLambda` now takes a descriptor template argument.

The following bugs were encountered and fixed with this MR:
- mixed-domain vector-to-scalar reductions were bugged for the nonblocking backend: when the second (underlying) monoid domain type did not match its third (output) domain type, a compiler error would be returned.

2024-02-27 13:10 UTC, anyzelman approved these changes

2024-02-27 13:11 UTC, anyzelman commented
Found one more minor issue in nonblocking, now fixed -- re-running unit tests excluding the LPF ones.

2024-02-27 14:50 UTC, merged