268 provide grbsetmatrix out matrix mask matrix in
Algebraic-Programming/ALP pull request #314
Opened 2024-02-21 14:17 UTC by aleksamilisavljevic

Closes #268

2024-02-22 10:29 UTC, byjtew requested changes, later dismissed
Nice job, as for the unit-test, you could rely on the matrix factories that we have.
e.g: L masked by I should return I
L being a Lower triangular matrix 
I being an identity matrix

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/nonblocking/io.hpp
> +			internal::getRefMatrix( Mask ),
Variable name should be `mask` or `M`, not `Mask` otherwise it looks like a type-name

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +				const size_t k_col = mask_raw.row_index[ k ];
```suggestion
				const auto k_col = mask_raw.row_index[ k ];
```
Since we use `RTI`, `CIT`, etc.

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +			}
openMP reduction possible easily

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +					mask_coors.assign( k_col );
There's an openMP version of the assign, you can find it in other places in the code using the function `assignAsync` if you're in a parallel region

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +			#pragma omp parallel for simd
```suggestion
		#pragma omp parallel for simd
```

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +					const size_t CCS_index = C_col_index[ k_col ]++ + CCS_raw.col_start[ k_col ];
```suggestion
					const size_t CCS_index = C_col_index[ k_col ] + CCS_raw.col_start[ k_col ];
					C_col_index[ k_col ]++;
```

2024-02-22 10:29 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +		assert( old_nzc == nzc );
```suggestion
#ifndef NDEBUG
		for( size_t j = 0; j < ncols; ++j ) {
			assert( CCS_raw.col_start[ j + 1 ] - CCS_raw.col_start[ j ] ==
				C_col_index[ j ] );
		}
		assert( old_nzc == nzc );
#endif
```

2024-02-22 13:20 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +				if( utils::interpretMask< descr, MaskType >( true, mask_raw.values, k ) ) {
Will not compile if you test with void matrices, I am currently developing a version of interpretMask for matrices because this one only works for vectors

2024-02-26 13:30 UTC, byjtew commented on include/graphblas/reference/io.hpp
> +				if( utils::interpretMask< descr, MaskType >( true, mask_raw.values, k ) ) {
```c++
/** Specialisation for void-valued matrice's masks */
		template< Descriptor descriptor, typename MatrixDataType, typename ValuesType >
		static bool interpretMatrixMask(
			const bool &assigned,
			const ValuesType * const values,
			const size_t k,
			typename std::enable_if<
				!std::is_void< MatrixDataType >::value
			>::type * = nullptr
		) {
			return interpretMask< descriptor, ValuesType >( assigned, values, k );
		}

		/** Specialisation for void-valued matrice's masks */
		template< Descriptor descriptor, typename MatrixDataType, typename ValuesType >
		static bool interpretMatrixMask(
			const bool &assigned,
			const ValuesType * const,
			const size_t,
			typename std::enable_if<
				std::is_void< MatrixDataType >::value
			>::type * = nullptr
		) {
			// set default mask to false
			bool ret = assigned;
			// check whether we should return the inverted value
			if( descriptor & descriptors::invert_mask ) {
				return !ret;
			} else {
				return ret;
			}
		}
```

Add these two functions in `utils.hpp` and call them like this `utils::interpretMatrixMask< descr, MaskType >( true, mask_raw.getValues(), k_col )`

2024-02-27 09:52 UTC, aleksamilisavljevic commented on include/graphblas/reference/io.hpp
> +				if( utils::interpretMask< descr, MaskType >( true, mask_raw.values, k ) ) {
Done, thanks!

2024-02-27 09:52 UTC, aleksamilisavljevic commented on include/graphblas/reference/io.hpp
> +		assert( old_nzc == nzc );
Done, thanks!

2024-02-27 09:52 UTC, aleksamilisavljevic commented on include/graphblas/reference/io.hpp
> +					const size_t CCS_index = C_col_index[ k_col ]++ + CCS_raw.col_start[ k_col ];
Done, thanks!

2025-08-17 14:54 UTC, anyzelman commented
@aleksamilisavljevic @byjtew -- apologies, I thought this one was merged ages ago but found it still open just now. I've rebased it (and weirdly enough indeed a component from this MR was already in utils?) and will look at it more shortly: at the moment it builds but not sure if it passes unit tests, plus I see a spec for the missing primitive should still be provided). I'll take those remainder, hopefully small, steps over the coming days:)

2025-08-23 12:26 UTC, anyzelman commented
It's back up with unit tests passing, still a few TODOs:

- [x] check if it makes sense to unit test non-void to void, no-casting vs. casting, and void-to-void. At present, the unit test goes for non-casting and non-void to non-void only
- [x] unit test should check passing empty masks
- [x] BSP1D and hybrid implementations are missing
- [x] reference_omp variant is not yet fully parallel

2025-08-23 15:19 UTC, anyzelman commented
Upgraded unit test -- running the full suite before continuing some other time

2025-08-26 08:02 UTC, anyzelman commented
All tests pass at this point, by the way (test results from over the weekend). Only one TODO remaining, which is the parallelisation of this function in the `reference_omp` backend.

2026-02-20 14:31 UTC, anyzelman commented
Since it's almost done, some draft release notes:

A matrix copy operation with output mask (`grb::set( matrix, matrix, matrix )`) is added. This includes a specification as well as implementations for all current backends, plus an extension to make the unit test for all variants of `grb::set` that operate on matrices exhaustive in coverage (including for masked matrix copies, with and without casting, etc.).

Additionally, this MR:
 - moves the SPA buffer management class from `blas3.hpp` to `matrix.hpp`;
 - fixes incomplete handling of the `no_casting` descriptor of `grb::set` with matrix outputs;
 - fixes a missing include in `bsp1d/init.hpp`;
 - cleans up minor inaccuracies and typos to the specifications in `io.hpp`;
 - expands on the specification of mask inversion in the case of matrix outputs;
 - improves debug tracing; and,
 - as always, includes minor code style fixes.

Big thanks to @aleksamilisavljevic for providing the implementation for the reference backend, now finally merged!

2026-02-20 16:22 UTC, anyzelman commented
All tests indeed pass. Now factoring in the crs_only descriptor and then this should be ready for merge=)

2026-02-20 16:57 UTC, anyzelman submitted a review, later dismissed

2026-02-20 17:00 UTC, anyzelman commented
@byjtew Hi Benjamin - you had requested changes here a long long time ago -- just making sure if dismissing your review is ok for you, or whether you want to have a look (and have the time for it--ofc totally ok if not!)

(It's just that github would block the merge in the current situation given your past review:)

2026-02-20 17:39 UTC, byjtew commented
> @byjtew Hi Benjamin - you had requested changes here a long long time ago -- just making sure if dismissing your review is ok for you, or whether you want to have a look (and have the time for it--ofc totally ok if not!)
> 
> 
> 
> (It's just that github would block the merge in the current situation given your past review:)

Yes sorry, you can dismiss my review indeed ahah @anyzelman

2026-02-21 14:54 UTC, anyzelman approved these changes

2026-02-21 15:00 UTC, merged